In [15]:
import pandas as pd
import numpy as np

In [16]:
df2021=pd.read_csv("ipl_2021.csv")
df2022=pd.read_csv("ipl_2022.csv")
bat2023=pd.read_csv("ipl_2023_bat.csv")
bowl2023=pd.read_csv("ipl_2023_bowl.csv")
bat2024=pd.read_csv("ipl_2024_bat.csv")
bowl2024=pd.read_csv("ipl_2024_bowl.csv")

In [17]:
df2021.head()

,Name,Team,Batting_Hand,Bowling_Type,Role,Matches,Innings,Not Outs,Runs,Highest,...,Innings_Bowl,Balls,Runs_Given,Wickets,BBI,Economy,B_Average,BSR,5W,10W
0,Ruturaj Gaikwad,Chennai Super Kings,Right,Right-arm offbreak,BATSMAN,6,6,2,204,72,...,0,0,0,0,0,0.0,0.0,0.00,0,0
1,KL Rahul,Punjab Kings,Right,NaN,WICKET KEEPER,81,72,13,2647,132,...,0,0,0,0,0,0.0,0.0,0.00,0,0
2,David Warner,Sunrisers Hyderabad,Left,Right-arm legbreak,BATSMAN,142,142,19,5254,126,...,1,1,2,0,0/2,0.0,0.0,0.00,0,0
3,Jonny Bairstow,Sunrisers Hyderabad,Right,Right-arm medium,WICKET KEEPER,21,21,2,790,114,...,0,0,0,0,0,0.0,0.0,0.00,0,0
4,Chris Gayle,Punjab Kings,Left,Right-arm offbreak,BATSMAN,132,131,15,4772,175,...,38,554,729,18,Mar-21,7.9,40.5,30.78,0,0

In [18]:
df2021 = df2021.rename(columns={
    "Name": "Name",
    "Team": "Team",
    "Matches": "Matches",
    "Innings": "Innings",
    "Runs": "Runs",
    "Average": "BattingAverage",
    "SR": "BattingStrikeRate",
    "BF": "BallsFaced",
    "50": "50s",
    "100": "100s",
    "4": "4s",
    "6": "6s",
    "Balls": "BallsBowled",
    "Runs_Given": "RunsConceded",
    "Wickets": "Wickets",
    "Economy": "Economy",
    "B_Average": "BowlingAverage",
    "BSR": "BowlingStrikeRate"
})

df2021["Year"] = 2021

In [19]:
df2022 = df2022.rename(columns={
    "MatchPlayed": "Matches",
    "InningsBatted": "Innings",
    "RunsScored": "Runs",
    "BattingAVG": "BattingAverage",
    "BattingS/R": "BattingStrikeRate",
    "HighestInnScore": "HighestScore",
    "100s": "100s",
    "50s": "50s",
    "4s": "4s",
    "6s": "6s",
    "InningsBowled": "BowlingInnings",
    "Overs": "Overs",
    "RunsConceded": "RunsConceded",
    "EconomyRate": "Economy",
    "BowlingAVG": "BowlingAverage",
    "S/R": "BowlingStrikeRate",
    "National Side": "Country",
    "Type": "Role"
})

df2022["Year"] = 2022

In [20]:
bat2023 = bat2023.rename(columns={
    "Player Name": "Name",
    "Team Name": "Team",
    "Matches Played": "Matches",
    "Total runs": "Runs",
    "Average": "BattingAverage",
    "Strike Rate": "BattingStrikeRate",
    "Balls Faced": "BallsFaced",
    "50": "50s",
    "100": "100s",
    "4s": "4s",
    "6s": "6s"
})

In [21]:
bowl2023 = bowl2023.rename(columns={
    "Player Name": "Name",
    "Team Name": "Team",
    "Matches": "Matches",
    "Balls Bowled": "BallsBowled",
    "Runs": "RunsConceded",
    "Wickets": "Wickets",
    "Bowling Average": "BowlingAverage",
    "Economy Rate": "Economy",
    "Strike Rate": "BowlingStrikeRate"
})

In [22]:
df2023 = bat2023.merge(
    bowl2023[
        [
            "Name",
            "Team",
            "BallsBowled",
            "RunsConceded",
            "Wickets",
            "BowlingAverage",
            "Economy",
            "BowlingStrikeRate"
        ]
    ],
    on=["Name", "Team"],
    how="outer"
)

df2023["Year"] = 2023

In [23]:
bat2024 = bat2024.rename(columns={
    "Player Name": "Name",
    "Team Name": "Team",
    "Matches Played": "Matches",
    "Total runs": "Runs",
    "Average": "BattingAverage",
    "Strike Rate": "BattingStrikeRate",
    "Balls Faced": "BallsFaced",
    "50": "50s",
    "100": "100s",
    "4s": "4s",
    "6s": "6s"
})

bowl2024 = bowl2024.rename(columns={
    "Player Name": "Name",
    "Team Name": "Team",
    "Matches": "Matches",
    "Balls Bowled": "BallsBowled",
    "Runs": "RunsConceded",
    "Wickets": "Wickets",
    "Bowling Average": "BowlingAverage",
    "Economy Rate": "Economy",
    "Strike Rate": "BowlingStrikeRate"
})

df2024 = bat2024.merge(
    bowl2024[
        [
            "Name",
            "Team",
            "BallsBowled",
            "RunsConceded",
            "Wickets",
            "BowlingAverage",
            "Economy",
            "BowlingStrikeRate"
        ]
    ],
    on=["Name", "Team"],
    how="outer"
)

df2024["Year"] = 2024

In [24]:
df2023.head(20)

,Name,Team,Runs,Year,Matches,Innings,Not Outs,Highest Score,BattingAverage,BallsFaced,...,50s,100s,4s,6s,BallsBowled,RunsConceded,Wickets,BowlingAverage,Economy,BowlingStrikeRate
0,A Badoni,LSG,238.0,2023,15.0,12.0,2.0,59*,23.80,172.0,...,1.0,0.0,13.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN
1,A Madhwal,MI,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,153.0,219.0,14.0,15.64,8.58,10.92
2,A Manohar,GT,114.0,2023,9.0,6.0,0.0,42,19.00,83.0,...,0.0,0.0,6.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN
3,A Mishra,LSG,19.0,2023,7.0,1.0,0.0,19,19.00,30.0,...,0.0,0.0,2.0,0.0,114.0,149.0,7.0,21.28,7.84,16.28
4,A Nortje,DC,37.0,2023,10.0,7.0,4.0,23*,12.33,29.0,...,0.0,0.0,6.0,0.0,240.0,364.0,10.0,36.40,9.10,24.00
5,A Taide,PBKS,186.0,2023,7.0,7.0,0.0,66,26.57,129.0,...,2.0,0.0,20.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN
6,A Zampa,RR,10.0,2023,6.0,3.0,0.0,7,3.33,16.0,...,0.0,0.0,0.0,0.0,132.0,188.0,8.0,23.50,8.54,16.50
7,AD Russell,KKR,227.0,2023,14.0,14.0,3.0,42,20.63,156.0,...,0.0,0.0,13.0,18.0,91.0,172.0,7.0,24.57,11.34,13.00
8,AJ Hosein,SRH,16.0,2023,1.0,1.0,1.0,16*,0.00,10.0,...,0.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
9,AK Markram,SRH,248.0,2023,13.0,13.0,2.0,50,22.54,197.0,...,1.0,0.0,18.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN
10,AM Rahane,CSK,326.0,2023,14.0,11.0,1.0,71*,32.60,189.0,...,2.0,0.0,24.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN
11,AR Patel,DC,283.0,2023,14.0,13.0,3.0,54,28.30,203.0,...,1.0,0.0,21.0,15.0,282.0,338.0,11.0,30.72,7.19,25.63
12,AS Joseph,GT,7.0,2023,7.0,2.0,2.0,7*,0.00,12.0,...,0.0,0.0,1.0,0.0,144.0,225.0,7.0,32.14,9.37,20.57
13,AS Roy,KKR,23.0,2023,4.0,4.0,2.0,13*,11.50,19.0,...,0.0,0.0,3.0,0.0,48.0,65.0,3.0,21.66,8.12,16.00
14,AS Tendulkar,MI,13.0,2023,4.0,1.0,0.0,13,13.00,9.0,...,0.0,0.0,0.0,1.0,59.0,92.0,3.0,30.66,9.35,19.66
15,AT Rayudu,CSK,158.0,2023,16.0,12.0,2.0,27*,15.80,113.0,...,0.0,0.0,10.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN
16,AU Rashid,SRH,22.0,2023,2.0,2.0,0.0,18,11.00,16.0,...,0.0,0.0,2.0,1.0,42.0,56.0,2.0,28.00,8.00,21.00
17,Abdul Samad,SRH,169.0,2023,9.0,8.0,4.0,37*,42.25,128.0,...,0.0,0.0,10.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN
18,Abhishek Sharma,SRH,226.0,2023,11.0,11.0,0.0,67,20.54,157.0,...,2.0,0.0,28.0,6.0,72.0,124.0,2.0,62.00,10.33,36.00
19,Abishek Porel,DC,33.0,2023,4.0,4.0,0.0,20,8.25,31.0,...,0.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
team_mapping = {
    "Chennai Super Kings": "CSK",
    "Mumbai Indians": "MI",
    "Royal Challengers Bangalore": "RCB",
    "Royal Challengers Bengaluru": "RCB",
    "Kolkata Knight Riders": "KKR",
    "Delhi Capitals": "DC",
    "Delhi Daredevils": "DD",
    "Punjab Kings": "PBKS",
    "Kings XI Punjab": "KXIP",
    "Rajasthan Royals": "RR",
    "Sunrisers Hyderabad": "SRH",
    "Deccan Chargers": "DCG",
    "Lucknow Super Giants": "LSG",
    "Gujarat Titans": "GT",
    "Gujarat Lions": "GL",
    "Rising Pune Supergiant": "RPS",
    "Rising Pune Supergiants": "RPS",
    "Pune Warriors India": "PWI",
    "Kochi Tuskers Kerala": "KTK"
}

df2021["Team"] = df2021["Team"].replace(team_mapping)

In [26]:
sorted(df2021["Team"].unique())

['CSK', 'DC', 'KKR', 'MI', 'PBKS', 'RCB', 'RR', 'SRH']

In [27]:
from sklearn.preprocessing import MinMaxScaler

# Features used for batting rating
bat_features = [
    "Runs",
    "BattingAverage",
    "BattingStrikeRate",
    "50s",
    "100s",
    "4s",
    "6s"
]

# Normalize
scaler = MinMaxScaler()

df2024[[f"{col}_norm" for col in bat_features]] = scaler.fit_transform(
    df2024[bat_features].fillna(0)
)

In [29]:
# Weighted batting score (0-1)
df2024["BattingScore"] = (
    0.35 * df2024["Runs_norm"] +
    0.23 * df2024["BattingAverage_norm"] +
    0.24 * df2024["BattingStrikeRate_norm"] +
    0.07 * df2024["50s_norm"] +
    0.02 * df2024["100s_norm"] +
    0.03 * df2024["4s_norm"] +
    0.06 * df2024["6s_norm"]
)
# Convert to FIFA-style rating (50-99)
min_score = df2024["BattingScore"].min()
max_score = df2024["BattingScore"].max()

df2024["BattingRating"] = (
    65 +
    (df2024["BattingScore"] - min_score) /
    (max_score - min_score) * 34
).round().astype(int)

In [30]:
df2024[["Name", "BattingScore", "BattingRating"]].sort_values(
    "BattingRating",
    ascending=False
).head(40)

                     Name  BattingScore  BattingRating
177               V Kohli      0.864814             99
118               R Parag      0.703999             93
127            RD Gaikwad      0.702647             93
102              N Pooran      0.718098             93
173               TM Head      0.712119             93
156             SV Samson      0.678367             92
17        Abhishek Sharma      0.629817             90
44              H Klaasen      0.629471             90
153             SP Narine      0.626187             90
111               PD Salt      0.610599             89
27        B Sai Sudharsan      0.621941             89
169              T Stubbs      0.620790             89
52        J Fraser-McGurk      0.589292             88
134               RR Pant      0.579069             88
66               KL Rahul      0.595707             88
133            RM Patidar      0.567294             87
40           F du Plessis      0.551890             87
182               VR Iyer      0.571900             87
107        NT Tilak Varma      0.555159             87
161        Shashank Singh      0.533231             86
142                S Dube      0.544758             86
162          Shubman Gill      0.538693             86
145              SA Yadav      0.518745             85
128             RG Sharma      0.513178             85
186           YBK Jaiswal      0.516939             85
63             KD Karthik      0.509513             85
91             MP Stoinis      0.499643             85
94               MS Dhoni      0.475492             84
154               SS Iyer      0.491034             84
54             JC Buttler      0.483274             84
18          Abishek Porel      0.466095             83
60   K Nitish Kumar Reddy      0.446612             83
38            DJ Mitchell      0.425798             82
124             RA Jadeja      0.440180             82
115     Prabhsimran Singh      0.443660             82
183              WG Jacks      0.427447             82
9              AD Russell      0.416026             81
57            JM Bairstow      0.418373             81
51           Ishan Kishan      0.407738             81
33              DA Miller      0.383918             80

In [31]:
df2024.drop(columns=[f"{col}_norm" for col in bat_features], inplace=True)

In [32]:
from sklearn.preprocessing import MinMaxScaler

bowl_features = [
    "Wickets",
    "BowlingAverage",
    "Economy",
    "BowlingStrikeRate"
]

scaler = MinMaxScaler()

df2024[[f"{col}_norm" for col in bowl_features]] = scaler.fit_transform(
    df2024[bowl_features].fillna(df2024[bowl_features].max())
)

# Invert lower-is-better metrics
df2024["BowlingAverage_norm"] = 1 - df2024["BowlingAverage_norm"]
df2024["Economy_norm"] = 1 - df2024["Economy_norm"]
df2024["BowlingStrikeRate_norm"] = 1 - df2024["BowlingStrikeRate_norm"]

In [33]:
df2024["BowlingScore"] = (
    0.50 * df2024["Wickets_norm"] +
    0.20 * df2024["BowlingAverage_norm"] +
    0.20 * df2024["Economy_norm"] +
    0.10 * df2024["BowlingStrikeRate_norm"]
)
# Convert BowlingScore to BowlingRating
min_score = df2024["BowlingScore"].min()
max_score = df2024["BowlingScore"].max()

df2024["BowlingRating"] = (
    50 +
    (df2024["BowlingScore"] - min_score) /
    (max_score - min_score) * 49
).round().astype(int)

In [34]:
df2024[
    ["Name", "Wickets", "Economy", "BowlingRating"]
].sort_values(
    "BowlingRating",
    ascending=False
).head(20)

                  Name  Wickets  Economy  BowlingRating
46            HV Patel     24.0     9.73             99
56           JJ Bumrah     20.0     6.48             97
29            CV Varun     21.0     8.04             97
9           AD Russell     19.0    10.05             93
49        Harshit Rana     19.0     9.08             93
153          SP Narine     17.0     6.69             92
168        T Natarajan     19.0     9.05             92
24          Avesh Khan     19.0     9.59             91
23      Arshdeep Singh     19.0    10.03             91
112         PJ Cummins     18.0     9.27             89
71       Kuldeep Yadav     16.0     8.65             89
174       TU Deshpande     17.0     8.83             89
187          YS Chahal     18.0     9.41             89
65            KK Ahmed     17.0     9.58             88
99        Mukesh Kumar     17.0    10.36             88
170           TA Boult     16.0     8.30             88
79         M Pathirana     13.0     7.68             87
84            MA Starc     17.0    10.61             87
150          SM Curran     16.0    10.14             87
100  Mustafizur Rahman     14.0     9.26             85

In [35]:
df2024.drop(
    columns=[f"{col}_norm" for col in bowl_features],
    inplace=True
)

In [36]:
def assign_role(row):
    if row["BattingRating"] >= 73 and row["BowlingRating"] >= 77:
        return "All-Rounder"
    elif row["BattingRating"] >= row["BowlingRating"]:
        return "Batsman"
    else:
        return "Bowler"
    
df2024["Role"] = df2024.apply(assign_role, axis=1)

In [37]:
df2024["Role"].value_counts()

Role
Batsman        92
Bowler         88
All-Rounder    11
Name: count, dtype: int64

In [38]:
def calculate_ovr(row):
    if row["Role"] == "Batsman":
        return round(
            0.90 * row["BattingRating"] +
            0.10 * row["BowlingRating"]
        )

    elif row["Role"] == "Bowler":
        return round(
            0.90 * row["BowlingRating"] +
            0.10 * row["BattingRating"]
        )

    elif row["Role"] == "All-Rounder":
        return round(
            0.55 * row["BattingRating"] +
            0.45 * row["BowlingRating"]
        )

    return round((row["BattingRating"] + row["BowlingRating"]) / 2)

In [39]:
df2024["OVR"] = df2024.apply(calculate_ovr, axis=1)

In [40]:
df2024[
    ["Name", "Role", "BattingRating", "BowlingRating", "OVR"]
].sort_values("OVR", ascending=False).head(25)

                Name         Role  BattingRating  BowlingRating  OVR
177          V Kohli      Batsman             99             76   97
46          HV Patel       Bowler             68             99   96
56         JJ Bumrah       Bowler             68             97   94
29          CV Varun       Bowler             65             97   94
102         N Pooran      Batsman             93             76   91
118          R Parag      Batsman             93             76   91
127       RD Gaikwad      Batsman             93             76   91
173          TM Head      Batsman             93             76   91
153        SP Narine  All-Rounder             90             92   91
49      Harshit Rana       Bowler             65             93   90
156        SV Samson      Batsman             92             76   90
168      T Natarajan       Bowler             65             92   89
44         H Klaasen      Batsman             90             76   89
23    Arshdeep Singh       Bowler             70             91   89
24        Avesh Khan       Bowler             71             91   89
17   Abhishek Sharma      Batsman             90             70   88
27   B Sai Sudharsan      Batsman             89             76   88
169         T Stubbs      Batsman             89             76   88
111          PD Salt      Batsman             89             76   88
66          KL Rahul      Batsman             88             76   87
134          RR Pant      Batsman             88             76   87
174     TU Deshpande       Bowler             65             89   87
71     Kuldeep Yadav       Bowler             72             89   87
52   J Fraser-McGurk      Batsman             88             76   87
187        YS Chahal       Bowler             65             89   87

In [41]:
from sklearn.preprocessing import MinMaxScaler

def create_cards1(df):
    df = df.copy()

    # ---------------- Batting Rating ----------------
    bat_features = [
        "Runs",
        "BattingAverage",
        "BattingStrikeRate",
        "50s",
        "100s",
        "4s",
        "6s"
    ]

    scaler = MinMaxScaler()

    df[[f"{c}_norm" for c in bat_features]] = scaler.fit_transform(
        df[bat_features].fillna(0)
    )

    df["BattingScore"] = (
        0.35 * df["Runs_norm"] +
        0.23 * df["BattingAverage_norm"] +
        0.24 * df["BattingStrikeRate_norm"] +
        0.07 * df["50s_norm"] +
        0.02 * df["100s_norm"] +
        0.03 * df["4s_norm"] +
        0.06 * df["6s_norm"]
    )

    min_score = df["BattingScore"].min()
    max_score = df["BattingScore"].max()

    df["BattingRating"] = (
        65 + (df["BattingScore"] - min_score) /
        (max_score - min_score) * 34
    ).round().astype(int)

    # ---------------- Bowling Rating ----------------

    bowl_features = [
        "Wickets",
        "BowlingAverage",
        "Economy",
        "BowlingStrikeRate"
    ]

    df[[f"{c}_norm" for c in bowl_features]] = scaler.fit_transform(
        df[bowl_features].fillna(df[bowl_features].max())
    )

    df["BowlingAverage_norm"] = 1 - df["BowlingAverage_norm"]
    df["Economy_norm"] = 1 - df["Economy_norm"]
    df["BowlingStrikeRate_norm"] = 1 - df["BowlingStrikeRate_norm"]

    df["BowlingScore"] = (
        0.50 * df["Wickets_norm"] +
        0.20 * df["BowlingAverage_norm"] +
        0.20 * df["Economy_norm"] +
        0.10 * df["BowlingStrikeRate_norm"]
    )

    min_score = df["BowlingScore"].min()
    max_score = df["BowlingScore"].max()

    df["BowlingRating"] = (
        50 + (df["BowlingScore"] - min_score) /
        (max_score - min_score) * 49
    ).round().astype(int)

    # ---------------- Role ----------------
    def assign_role(row):
        if row["BattingRating"] >= 78 and row["BowlingRating"] >= 79:
            return "All-Rounder"
        elif row["BattingRating"] >= row["BowlingRating"]:
            return "Batsman"
        else:
            return "Bowler"
    
    df2024["Role"] = df2024.apply(assign_role, axis=1)

    df["Role"] = df.apply(assign_role, axis=1)

    # ---------------- Overall ----------------

    def calculate_ovr(row):
        if row["Role"] == "Batsman":
            return round(0.90 * row["BattingRating"] + 0.10 * row["BowlingRating"])

        elif row["Role"] == "Bowler":
            return round(0.90 * row["BowlingRating"] + 0.10 * row["BattingRating"])

        elif row["Role"] == "All-Rounder":
            return round(0.55 * row["BattingRating"] + 0.45 * row["BowlingRating"])

    df["OVR"] = df.apply(calculate_ovr, axis=1)

    # Remove temporary normalized columns
    drop_cols = (
        [f"{c}_norm" for c in bat_features] +
        [f"{c}_norm" for c in bowl_features]
    )

    df.drop(columns=drop_cols, inplace=True)

    return df

In [42]:
from sklearn.preprocessing import MinMaxScaler

def create_cards2(df):
    df = df.copy()

    # ---------------- Batting Rating ----------------
    bat_features = [
        "Runs",
        "BattingAverage",
        "BattingStrikeRate",
        "50s",
        "100s",
        "4s",
        "6s"
    ]

    scaler = MinMaxScaler()

    df[[f"{c}_norm" for c in bat_features]] = scaler.fit_transform(
        df[bat_features].fillna(0)
    )

    df["BattingScore"] = (
        0.35 * df["Runs_norm"] +
        0.23 * df["BattingAverage_norm"] +
        0.24 * df["BattingStrikeRate_norm"] +
        0.07 * df["50s_norm"] +
        0.02 * df["100s_norm"] +
        0.03 * df["4s_norm"] +
        0.06 * df["6s_norm"]
    )

    min_score = df["BattingScore"].min()
    max_score = df["BattingScore"].max()

    df["BattingRating"] = (
        65 + (df["BattingScore"] - min_score) /
        (max_score - min_score) * 34
    ).round().astype(int)

    # ---------------- Bowling Rating ----------------

    bowl_features = [
        "Wickets",
        "BowlingAverage",
        "Economy",
        "BowlingStrikeRate"
    ]

    df[[f"{c}_norm" for c in bowl_features]] = scaler.fit_transform(
        df[bowl_features].fillna(df[bowl_features].max())
    )

    df["BowlingAverage_norm"] = 1 - df["BowlingAverage_norm"]
    df["Economy_norm"] = 1 - df["Economy_norm"]
    df["BowlingStrikeRate_norm"] = 1 - df["BowlingStrikeRate_norm"]

    df["BowlingScore"] = (
        0.50 * df["Wickets_norm"] +
        0.20 * df["BowlingAverage_norm"] +
        0.20 * df["Economy_norm"] +
        0.10 * df["BowlingStrikeRate_norm"]
    )

    min_score = df["BowlingScore"].min()
    max_score = df["BowlingScore"].max()

    df["BowlingRating"] = (
        50 + (df["BowlingScore"] - min_score) /
        (max_score - min_score) * 49
    ).round().astype(int)

    # ---------------- Role ----------------
    def assign_role(row):
        if row["BattingRating"] >= 80 and row["BowlingRating"] >= 77:
            return "All-Rounder"
        elif row["BattingRating"] >= row["BowlingRating"]:
            return "Batsman"
        else:
            return "Bowler"
    
    df2024["Role"] = df2024.apply(assign_role, axis=1)

    df["Role"] = df.apply(assign_role, axis=1)

    # ---------------- Overall ----------------

    def calculate_ovr(row):
        if row["Role"] == "Batsman":
            return round(0.90 * row["BattingRating"] + 0.10 * row["BowlingRating"])

        elif row["Role"] == "Bowler":
            return round(0.90 * row["BowlingRating"] + 0.10 * row["BattingRating"])

        elif row["Role"] == "All-Rounder":
            return round(0.55 * row["BattingRating"] + 0.45 * row["BowlingRating"])

    df["OVR"] = df.apply(calculate_ovr, axis=1)

    # Remove temporary normalized columns
    drop_cols = (
        [f"{c}_norm" for c in bat_features] +
        [f"{c}_norm" for c in bowl_features]
    )

    df.drop(columns=drop_cols, inplace=True)

    return df

In [43]:
from sklearn.preprocessing import MinMaxScaler

def create_cards3(df):
    df = df.copy()

    # ---------------- Batting Rating ----------------
    bat_features = [
        "Runs",
        "BattingAverage",
        "BattingStrikeRate",
        "50s",
        "100s",
        "4s",
        "6s"
    ]

    scaler = MinMaxScaler()

    df[[f"{c}_norm" for c in bat_features]] = scaler.fit_transform(
        df[bat_features].fillna(0)
    )

    df["BattingScore"] = (
        0.35 * df["Runs_norm"] +
        0.23 * df["BattingAverage_norm"] +
        0.24 * df["BattingStrikeRate_norm"] +
        0.07 * df["50s_norm"] +
        0.02 * df["100s_norm"] +
        0.03 * df["4s_norm"] +
        0.06 * df["6s_norm"]
    )

    min_score = df["BattingScore"].min()
    max_score = df["BattingScore"].max()

    df["BattingRating"] = (
        65 + (df["BattingScore"] - min_score) /
        (max_score - min_score) * 34
    ).round().astype(int)

    # ---------------- Bowling Rating ----------------

    bowl_features = [
        "Wickets",
        "BowlingAverage",
        "Economy",
        "BowlingStrikeRate"
    ]

    df[[f"{c}_norm" for c in bowl_features]] = scaler.fit_transform(
        df[bowl_features].fillna(df[bowl_features].max())
    )

    df["BowlingAverage_norm"] = 1 - df["BowlingAverage_norm"]
    df["Economy_norm"] = 1 - df["Economy_norm"]
    df["BowlingStrikeRate_norm"] = 1 - df["BowlingStrikeRate_norm"]

    df["BowlingScore"] = (
        0.50 * df["Wickets_norm"] +
        0.20 * df["BowlingAverage_norm"] +
        0.20 * df["Economy_norm"] +
        0.10 * df["BowlingStrikeRate_norm"]
    )

    min_score = df["BowlingScore"].min()
    max_score = df["BowlingScore"].max()

    df["BowlingRating"] = (
        50 + (df["BowlingScore"] - min_score) /
        (max_score - min_score) * 49
    ).round().astype(int)

    # ---------------- Role ----------------
    def assign_role(row):
        if row["BattingRating"] >= 72 and row["BowlingRating"] >= 73:
            return "All-Rounder"
        elif row["BattingRating"] >= row["BowlingRating"]:
            return "Batsman"
        else:
            return "Bowler"
    
    df2024["Role"] = df2024.apply(assign_role, axis=1)

    df["Role"] = df.apply(assign_role, axis=1)

    # ---------------- Overall ----------------

    def calculate_ovr(row):
        if row["Role"] == "Batsman":
            return round(0.90 * row["BattingRating"] + 0.10 * row["BowlingRating"])

        elif row["Role"] == "Bowler":
            return round(0.90 * row["BowlingRating"] + 0.10 * row["BattingRating"])

        elif row["Role"] == "All-Rounder":
            return round(0.55 * row["BattingRating"] + 0.45 * row["BowlingRating"])

    df["OVR"] = df.apply(calculate_ovr, axis=1)

    # Remove temporary normalized columns
    drop_cols = (
        [f"{c}_norm" for c in bat_features] +
        [f"{c}_norm" for c in bowl_features]
    )

    df.drop(columns=drop_cols, inplace=True)

    return df

In [44]:
from sklearn.preprocessing import MinMaxScaler

def create_cards4(df):
    df = df.copy()

    # ---------------- Batting Rating ----------------
    bat_features = [
        "Runs",
        "BattingAverage",
        "BattingStrikeRate",
        "50s",
        "100s",
        "4s",
        "6s"
    ]

    scaler = MinMaxScaler()

    df[[f"{c}_norm" for c in bat_features]] = scaler.fit_transform(
        df[bat_features].fillna(0)
    )

    df["BattingScore"] = (
        0.35 * df["Runs_norm"] +
        0.23 * df["BattingAverage_norm"] +
        0.24 * df["BattingStrikeRate_norm"] +
        0.07 * df["50s_norm"] +
        0.02 * df["100s_norm"] +
        0.03 * df["4s_norm"] +
        0.06 * df["6s_norm"]
    )

    min_score = df["BattingScore"].min()
    max_score = df["BattingScore"].max()

    df["BattingRating"] = (
        65 + (df["BattingScore"] - min_score) /
        (max_score - min_score) * 34
    ).round().astype(int)

    # ---------------- Bowling Rating ----------------

    bowl_features = [
        "Wickets",
        "BowlingAverage",
        "Economy",
        "BowlingStrikeRate"
    ]

    df[[f"{c}_norm" for c in bowl_features]] = scaler.fit_transform(
        df[bowl_features].fillna(df[bowl_features].max())
    )

    df["BowlingAverage_norm"] = 1 - df["BowlingAverage_norm"]
    df["Economy_norm"] = 1 - df["Economy_norm"]
    df["BowlingStrikeRate_norm"] = 1 - df["BowlingStrikeRate_norm"]

    df["BowlingScore"] = (
        0.50 * df["Wickets_norm"] +
        0.20 * df["BowlingAverage_norm"] +
        0.20 * df["Economy_norm"] +
        0.10 * df["BowlingStrikeRate_norm"]
    )

    min_score = df["BowlingScore"].min()
    max_score = df["BowlingScore"].max()

    df["BowlingRating"] = (
        50 + (df["BowlingScore"] - min_score) /
        (max_score - min_score) * 49
    ).round().astype(int)

    # ---------------- Role ----------------
    def assign_role(row):
        if row["BattingRating"] >= 73 and row["BowlingRating"] >= 77:
            return "All-Rounder"
        elif row["BattingRating"] >= row["BowlingRating"]:
            return "Batsman"
        else:
            return "Bowler"
    
    df2024["Role"] = df2024.apply(assign_role, axis=1)

    df["Role"] = df.apply(assign_role, axis=1)

    # ---------------- Overall ----------------

    def calculate_ovr(row):
        if row["Role"] == "Batsman":
            return round(0.90 * row["BattingRating"] + 0.10 * row["BowlingRating"])

        elif row["Role"] == "Bowler":
            return round(0.90 * row["BowlingRating"] + 0.10 * row["BattingRating"])

        elif row["Role"] == "All-Rounder":
            return round(0.55 * row["BattingRating"] + 0.45 * row["BowlingRating"])

    df["OVR"] = df.apply(calculate_ovr, axis=1)

    # Remove temporary normalized columns
    drop_cols = (
        [f"{c}_norm" for c in bat_features] +
        [f"{c}_norm" for c in bowl_features]
    )

    df.drop(columns=drop_cols, inplace=True)

    return df

In [45]:
df2021 = create_cards1(df2021)
df2022 = create_cards2(df2022)
df2023 = create_cards3(df2023)
df2024 = create_cards4(df2024)

In [46]:
df2024["Role"].value_counts().reindex(
    ["Batsman", "All-Rounder", "Bowler"]
).fillna(0).astype(int)

Role
Batsman        92
All-Rounder    11
Bowler         88
Name: count, dtype: int64

In [47]:
master_df = pd.concat(
    [df2021, df2022, df2023, df2024],
    ignore_index=True
)

master_df.reset_index(drop=True, inplace=True)

In [48]:
master_df["CardID"] = range(1, len(master_df) + 1)

In [49]:
master_df.iloc[80:100]

,Name,Team,Batting_Hand,Bowling_Type,Role,Matches,Innings,Not Outs,Runs,Highest,...,BowlingInnings,Overs,Maidens,Best,3s,5s,Mtc,Highest Score,0,CardID
80,Shivam Dube,RR,Left,Right-arm medium,Batsman,15.0,13.0,3.0,169.0,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81
81,Deepak Hooda,PBKS,Right,Right-arm offbreak,Batsman,68.0,50.0,13.0,625.0,62.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82
82,Sunil Narine,KKR,Left,Right-arm offbreak,All-Rounder,120.0,66.0,13.0,892.0,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83
83,N Jagadeesan,CSK,Right,NaN,Bowler,5.0,2.0,0.0,33.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84
84,Mohammad Nabi,SRH,Right,Right-arm offbreak,Batsman,14.0,11.0,2.0,146.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
85,Karn Sharma,CSK,Left,Right-arm legbreak,Bowler,68.0,35.0,14.0,317.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86
86,Harbhajan Singh,KKR,Right,Right-arm offbreak,All-Rounder,160.0,88.0,33.0,829.0,64.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87
87,Jofra Archer,RR,Right,Right-arm fast,Batsman,35.0,23.0,10.0,195.0,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88
88,Jason Holder,SRH,Right,Right-arm fast,Batsman,18.0,9.0,2.0,104.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89
89,Priyam Garg,SRH,Right,Right-arm medium,Bowler,14.0,10.0,1.0,133.0,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90
90,Shreevats Goswami,SRH,Left,NaN,Bowler,31.0,21.0,1.0,293.0,52.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91
91,Navdeep Saini,RCB,Right,Right-arm fast,Batsman,26.0,5.0,3.0,29.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92
92,Krishnappa Gowtham,CSK,Right,Right-arm offbreak,Batsman,24.0,19.0,6.0,186.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93
93,Aditya Tare,MI,Right,NaN,Bowler,35.0,28.0,4.0,339.0,59.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94
94,Pawan Negi,KKR,Left,Left-arm orthodox,Batsman,50.0,35.0,9.0,365.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95
95,Jasprit Bumrah,MI,Right,Right-arm fast,Bowler,92.0,13.0,10.0,40.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96
96,Yashasvi Jaiswal,RR,Left,Right-arm legbreak,Bowler,3.0,3.0,0.0,40.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97
97,Shreyas Gopal,RR,Right,Right-arm legbreak,Bowler,45.0,19.0,6.0,164.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98
98,Kagiso Rabada,DC,Left,Right-arm fast,Bowler,35.0,15.0,5.0,125.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99
99,James Neesham,MI,Left,Right-arm medium,Batsman,9.0,6.0,1.0,61.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100

In [52]:
cards = master_df[
    [
        "CardID",
        "Name",
        "Year",
        "Team",
        "Role",
        "BattingRating",
        "BowlingRating",
        "OVR",
        "CardType"
    ]
].copy()

In [ ]:
cards.head(20)

,CardID,Name,Year,Team,Role,BattingRating,BowlingRating,OVR,CardType
0,1,Ruturaj Gaikwad,2021,CSK,Batsman,82,78,82,Legacy
1,2,KL Rahul,2021,PBKS,Batsman,90,78,89,Legacy
2,3,David Warner,2021,SRH,Batsman,99,78,97,Legacy
3,4,Jonny Bairstow,2021,SRH,Batsman,83,78,82,Legacy
4,5,Chris Gayle,2021,PBKS,Batsman,98,67,95,Legacy
5,6,MS Dhoni,2021,CSK,Batsman,95,78,93,Legacy
6,7,AB de Villiers,2021,RCB,Batsman,97,78,95,Legacy
7,8,Kane Williamson,2021,SRH,Batsman,85,70,84,Legacy
8,9,Virat Kohli,2021,RCB,Batsman,99,53,94,Legacy
9,10,Steven Smith,2021,DC,Batsman,86,78,85,Legacy
10,11,Rishabh Pant,2021,DC,Batsman,87,78,86,Legacy
11,12,Jos Buttler,2021,RR,Batsman,85,78,84,Legacy
12,13,Shikhar Dhawan,2021,DC,Batsman,95,69,92,Legacy
13,14,Chris Lynn,2021,MI,Batsman,83,78,82,Legacy
14,15,David Miller,2021,RR,Batsman,85,78,84,Legacy
15,16,Shubman Gill,2021,KKR,Batsman,81,78,81,Legacy
16,17,Suresh Raina,2021,CSK,Batsman,96,67,93,Legacy
17,18,Faf du Plessis,2021,CSK,Batsman,85,65,83,Legacy
18,19,Nicholas Pooran,2021,PBKS,Batsman,82,78,82,Legacy
19,20,Basil Thampi,2021,SRH,Batsman,76,66,75,Legacy

In [ ]:
master_df.loc[master_df["Year"] == 2021, "CardType"] = "Legacy"
master_df.loc[master_df["Year"] == 2022, "CardType"] = "Icon"
master_df.loc[master_df["Year"] == 2023, "CardType"] = "Season"
master_df.loc[master_df["Year"] == 2024, "CardType"] = "Season"

In [73]:
from collections import Counter

def get_team_counts(team_ids, cards):
    team = cards[cards["CardID"].isin(team_ids)]

    return {
        "Team": Counter(team["Team"]),
        "Role": Counter(team["Role"]),
        "CardType": Counter(team["CardType"])
    }


def player_chemistry(player, counts):

    chem = 0

    # ---------- Team ----------
    team_count = counts["Team"][player["Team"]] + 1

    if team_count >= 3:
        chem += 2
    elif team_count == 2:
        chem += 1

    # ---------- Role ----------
    role_count = counts["Role"][player["Role"]] + 1

    if player["Role"] == "Batsman" and role_count <= 5:
        chem += 1

    elif player["Role"] == "Bowler" and role_count <= 4:
        chem += 1

    elif player["Role"] == "All-Rounder" and role_count <= 2:
        chem += 1

    # ---------- Card Type ----------
    card_count = counts["CardType"][player["CardType"]] + 1

    if card_count >= 2:
        chem += 1

    return min(chem, 3)

In [74]:
import random
import pandas as pd

def recommend_players(team_ids, cards, n=5):

    available = cards[~cards["CardID"].isin(team_ids)].copy()

    # Calculate counts ONLY ONCE
    counts = get_team_counts(team_ids, cards)

    recommendations = []

    for _, player in available.iterrows():

        chem = player_chemistry(player, counts)

        score = (
            player["OVR"] * 0.70 +
            chem * 8 +
            random.uniform(0, 5)
        )

        recommendations.append({
            "CardID": player["CardID"],
            "Name": player["Name"],
            "Team": player["Team"],
            "Role": player["Role"],
            "Year": player["Year"],
            "CardType": player["CardType"],
            "OVR": player["OVR"],
            "Chemistry": chem,
            "RecommendationScore": score
        })

    recommendations = pd.DataFrame(recommendations)

    recommendations = recommendations.sort_values(
        "RecommendationScore",
        ascending=False
    ).reset_index(drop=True)

    # -------- Tiers --------
    tier1 = recommendations.iloc[:5]
    tier2 = recommendations.iloc[5:15]
    tier3 = recommendations.iloc[15:40]

    # Random draft pattern
    patterns = [
        (2,2,1),
        (1,3,1),
        (1,2,2)
    ]

    weights = [0.7,0.2,0.1]

    elite, great, good = random.choices(
        patterns,
        weights=weights,
        k=1
    )[0]

    selected = pd.concat([
        tier1.sample(min(elite,len(tier1))),
        tier2.sample(min(great,len(tier2))),
        tier3.sample(min(good,len(tier3)))
    ])

    selected = selected.drop_duplicates("CardID")

    selected = selected.sample(frac=1).reset_index(drop=True)

    return selected

In [78]:
draft_team = []

while len(draft_team) < 11:

    print(f"\nPick {len(draft_team)+1}")

    options = recommend_players(draft_team, cards)

    print(options[[
        "CardID",
        "Name",
        "Team",
        "Role",
        "OVR",
        "CardType"
    ]])

    choice = options.iloc[0]["CardID"]   # Auto-select first player
    print(f"Selected: {choice}")

    if choice not in draft_team:
        draft_team.append(choice)

print("Draft Complete!")

Pick 1
   CardID                 Name Team     Role  OVR CardType
0       3         David Warner  SRH  Batsman   97   Legacy
1     252  Ravichandran Ashwin   RR   Bowler   94     Icon
2       7       AB de Villiers  RCB  Batsman   95   Legacy
3     595         Shubman Gill   GT  Batsman   96   Season
4     478         F du Plessis  RCB  Batsman   94   Season
Selected: 3

Pick 2
   CardID               Name Team         Role  OVR CardType
0      13     Shikhar Dhawan   DC      Batsman   92   Legacy
1      58       Dwayne Bravo  CSK  All-Rounder   88   Legacy
2       7     AB de Villiers  RCB      Batsman   95   Legacy
3     228  Bhuvneshwar Kumar  SRH       Bowler   94     Icon
4     127  Bhuvneshwar Kumar  SRH       Bowler   92   Legacy
Selected: 13

Pick 3
   CardID                 Name  Team     Role  OVR CardType
0     118       Sandeep Sharma   SRH   Bowler   87   Legacy
1     108  Ravichandran Ashwin    DC   Bowler   92   Legacy
2       5          Chris Gayle  PBKS  Batsman   95   Legacy
3      96       Jasprit Bumrah    MI   Bowler   87   Legacy
4      74         Sam Billings    DC   Bowler   78   Legacy
Selected: 118

Pick 4
   CardID                 Name Team     Role  OVR CardType
0     108  Ravichandran Ashwin   DC   Bowler   92   Legacy
1      33        Manish Pandey  SRH  Batsman   86   Legacy
2      38        Robin Uthappa  CSK  Batsman   91   Legacy
3     127    Bhuvneshwar Kumar  SRH   Bowler   92   Legacy
4      11         Rishabh Pant   DC  Batsman   86   Legacy
Selected: 108

Pick 5
   CardID               Name Team     Role  OVR CardType
0     687           KK Ahmed   DC   Bowler   86   Season
1     790        T Natarajan  SRH   Bowler   89   Season
2     372       David Warner   DC  Batsman   95     Icon
3     228  Bhuvneshwar Kumar  SRH   Bowler   94     Icon
4     127  Bhuvneshwar Kumar  SRH   Bowler   92   Legacy
Selected: 687

Pick 6
   CardID               Name Team     Role  OVR CardType
0     472          DA Warner   DC  Batsman   86   Season
1     103        Amit Mishra   DC   Bowler   96   Legacy
2      10       Steven Smith   DC  Batsman   85   Legacy
3     372       David Warner   DC  Batsman   95     Icon
4     127  Bhuvneshwar Kumar  SRH   Bowler   92   Legacy
Selected: 472

Pick 7
   CardID               Name Team     Role  OVR CardType
0      22     Ajinkya Rahane   DC  Batsman   88   Legacy
1     228  Bhuvneshwar Kumar  SRH   Bowler   94     Icon
2     534          MM Sharma   GT   Bowler   96   Season
3     639    Abhishek Sharma  SRH  Batsman   88   Season
4     482          H Klaasen  SRH  Batsman   87   Season
Selected: 22

Pick 8
   CardID               Name Team     Role  OVR CardType
0     791           T Stubbs   DC  Batsman   88   Season
1     790        T Natarajan  SRH   Bowler   89   Season
2     103        Amit Mishra   DC   Bowler   96   Legacy
3      11       Rishabh Pant   DC  Batsman   86   Legacy
4     228  Bhuvneshwar Kumar  SRH   Bowler   94     Icon
Selected: 791

Pick 9
   CardID               Name Team     Role  OVR CardType
0      10       Steven Smith   DC  Batsman   85   Legacy
1     639    Abhishek Sharma  SRH  Batsman   88   Season
2     674    J Fraser-McGurk   DC  Batsman   87   Season
3     228  Bhuvneshwar Kumar  SRH   Bowler   94     Icon
4     693      Kuldeep Yadav   DC   Bowler   87   Season
Selected: 10

Pick 10
   CardID           Name Team     Role  OVR CardType
0     795        TM Head  SRH  Batsman   91   Season
1     666      H Klaasen  SRH  Batsman   89   Season
2     103    Amit Mishra   DC   Bowler   96   Legacy
3     693  Kuldeep Yadav   DC   Bowler   87   Season
4     790    T Natarajan  SRH   Bowler   89   Season
Selected: 795

Pick 11
   CardID               Name Team     Role  OVR CardType
0     367     Shardul Thakur   DC   Bowler   81     Icon
1     228  Bhuvneshwar Kumar  SRH   Bowler   94     Icon
2      11       Rishabh Pant   DC  Batsman   86   Legacy
3     368         Axar Patel   DC   Bowler   87     Icon
4     540     Mohammed Shami   GT   Bowler   96   Season
Selected: 367
Draft Complete!

In [79]:
final_team = cards[cards["CardID"].isin(draft_team)]

display(final_team)

print("Average OVR :", round(final_team["OVR"].mean(),2))

,CardID,Name,Year,Team,Role,BattingRating,BowlingRating,OVR,CardType
2,3,David Warner,2021,SRH,Batsman,99,78,97,Legacy
9,10,Steven Smith,2021,DC,Batsman,86,78,85,Legacy
12,13,Shikhar Dhawan,2021,DC,Batsman,95,69,92,Legacy
21,22,Ajinkya Rahane,2021,DC,Batsman,90,73,88,Legacy
107,108,Ravichandran Ashwin,2021,DC,Bowler,74,94,92,Legacy
117,118,Sandeep Sharma,2021,SRH,Bowler,71,89,87,Legacy
366,367,Shardul Thakur,2022,DC,Bowler,72,82,81,Icon
471,472,DA Warner,2023,DC,Batsman,87,72,86,Season
686,687,KK Ahmed,2024,DC,Bowler,65,88,86,Season
790,791,T Stubbs,2024,DC,Batsman,89,76,88,Season
794,795,TM Head,2024,SRH,Batsman,93,76,91,Season

Average OVR : 88.45

In [80]:
cards.to_csv("cards.csv", index=False)